---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 14
    username: ((dockerhub-username))
    password: ((dockerhub-password))

inputs:
  - name: source

caches:
  - path: source/node-modules

run:
  path: bash
  dir: source
  args:
    - -exc
    - |
      yarn install
      yarn test-units
