---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 16
    username: ((dockerhub-username))
    password: ((dockerhub-password))

inputs:
  - name: source

params:
  FIRMWARE_DB_HOST: localhost
  FIRMWARE_DB_PORT: 27017
  FIRMWARE_DB_NAME: firmware-service-test
  FIRMWARE_DB_USERNAME: mongoadmin
  FIRMWARE_DB_PASSWORD: secret

caches:
  - path: source/node-modules

run:
  path: bash
  dir: source
  args:
    - -exc
    - |
      apt-get update
      apt-get install -y mongodb
      mkdir -p /data/db
      mongod &
      mongo 127.0.0.1:27017/firmware-service-test --eval 'db.createUser({"user": "mongoadmin", "pwd": "secret", "roles": ["dbOwner"]})'

      yarn install
      yarn test-integration
