resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: source
    type: git
    icon: github
    source:
      uri: git@github.com:petewall/firmware-service.git
      branch: main
      ignore_paths:
        - ci/*
        - ci/**
      private_key: ((github-repo-key))

  - name: pull-requests
    type: pull-request
    icon: github
    source:
      repository: petewall/firmware-service
      access_token: ((github-access-token))

  - name: node-js
    type: registry-image
    icon: nodejs
    source:
      repository: node
      tag: 14
      username: ((dockerhub-username))
      password: ((dockerhub-password))

jobs:
  - name: test
    plan:
      - in_parallel:
        - get: node-js
        - get: source
          trigger: true
      - task: lint
        image: node-js
        config:
          platform: linux
          inputs:
            - name: source
          run:
            dir: source
            path: yarn
            args: [run, lint]
      - task: test
        image: node-js
        config:
          platform: linux
          inputs:
            - name: source
          run:
            dir: source
            path: yarn
            args: [test]

  - name: test-pull-request
    plan:
      - in_parallel:
        - get: node-js
        - get: source
          resource: pull-requests
          trigger: true
          version: every
          params:
            integration_tool: rebase
      - put: pull-requests
        params:
          path: source
          status: pending
      - task: lint
        image: node-js
        config:
          platform: linux
          inputs:
            - name: source
          run:
            dir: source
            path: yarn
            args: [lint]
        on_failure:
          put: pull-requests
          params:
            path: source
            status: failure
      - task: test
        image: node-js
        config:
          platform: linux
          inputs:
            - name: source
          run:
            dir: source
            path: yarn
            args: [test]
        on_failure:
          put: pull-requests
          params:
            path: source
            status: failure
      - put: pull-requests
        params:
          path: source
          status: success